routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/threads', 'ThreadController@index');
Route::get('/threads/create', 'ThreadController@create');
Route::get('/threads/{channel}/{thread}', 'ThreadController@show');
Route::delete('/threads/{channel}/{thread}', 'ThreadController@destroy');
Route::post('/threads', 'ThreadController@store');
Route::get('/threads/{channel}', 'ThreadController@index');

Route::post('/threads/{channel}/{thread}/replies', 'ReplyController@store');
Route::delete('/replies/{reply}','ReplyController@destroy');
Route::patch('/replies/{reply}','ReplyController@update');

Route::post('/replies/{reply}/favorites', 'FavoriteController@store');
Route::delete('/replies/{reply}/favorites', 'FavoriteController@destroy');

Route::get('/profiles/{user}', 'ProfileController@show')->name('profile');

app/Models/Thread.php
<?php

namespace App\Models;

use App\Traits\RecordsActivity;
use Illuminate\Database\Eloquent\Model;

class Thread extends Model
{
    use RecordsActivity;

    protected $guarded = [];
    protected $withCount=['replies'];

    protected static function boot(){
        parent::boot();
        
        /*static::addGlobalScope('replyCount',function($builder){
            $builder->withCount('replies');
        });*/

        static::deleting(function($thread){
            $thread->replies->each->delete();
        });

    }

    public function path(){
    	return "/threads/{$this->channel->slug}/{$this->id}";
    }

    public function replies(){
    	return $this->hasMany(Reply::class);
    }

    /*public function getReplyCountAttribute(){
        return $this->replies()->count();
    }*/

    public function creator(){
    	return $this->belongsTo(User::class,'user_id');
    }

    public function channel(){
        return $this->belongsTo(Channel::class);
    }

    public function addReply($reply){
    	$this->replies()->create($reply);
    }

    public function scopeFilter($query, $filters){
        return $filters->apply($query);
    }

}

app/Http/Controllers/ThreadController.php
<?php

namespace App\Http\Controllers;

use App\Models\Thread;
use App\Models\Channel;
use App\Filters\ThreadFilters;
use Illuminate\Http\Request;

class ThreadController extends Controller
{
    public function __construct(){
        $this->middleware('auth')->except(['index','show']);
    }

    public function index(Channel $channel, ThreadFilters $filters)
    {

        $threads = $this->getThreads($channel,$filters);

        if(request()->wantsJson()){
            return $threads;
        }

        return view('threads.index',compact('threads'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('threads.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'title' =>  'required',
            'body' =>  'required',
            'channel_id' =>  'required|exists:channels,id'
        ]);
        $thread = Thread::create([
            'user_id'   =>  auth()->id(),
            'channel_id'     =>  $request->channel_id,
            'title'     =>  $request->title,
            'body'      =>  $request->body
        ]);
        return redirect($thread->path())->with('flash', 'Your reply has been left!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Thread  $thread
     * @return \Illuminate\Http\Response
     */
    public function show($channel,Thread $thread)
    {

        return view('threads.show',[
            'thread' => $thread,
            'replies' => $thread->replies()->paginate(20)
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Thread  $thread
     * @return \Illuminate\Http\Response
     */
    public function edit(Thread $thread)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Thread  $thread
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Thread $thread)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Thread  $thread
     * @return \Illuminate\Http\Response
     */
    public function destroy($channel,Thread $thread)
    {
        $this->authorize('update',$thread);
        /*if($thread->user_id != auth()->id()){
            abort(403, 'You do not have permission to do this.');
        }*/

        
        $thread->delete();
        if(request()->wantsJson()) return response([],204);
        return redirect('/threads');
    }

    protected function getThreads(Channel $channel,ThreadFilters $filters){
        
        $threads = Thread::latest()->filter($filters);

        if($channel->exists){
            $threads = $threads->where('channel_id',$channel->id);
        }
        //dd($threads->toSql());
        return  $threads->get();
    }
}

resources/views/threads/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Create a New Thread</div>

                <div class="panel-body">
                    <form action="/threads" method="post">
                    	{{ csrf_field()}}
                    	<div class="form-group">
                    		<label for="channel_id">Choose a Channel: </label>
                    		<select class="form-control" id="channel_id" name="channel_id" required>
                                <option  value="">Choose One...</option>
                                @foreach($channels as $channel)
                                <option value="{{ $channel->id }}" {{ old('channel_id') == $channel->id ? 'selected' : '' }}>
                                    {{ $channel->name }}
                                </option>
                                @endforeach
                                
                            </select>
                    	</div>
                        <div class="form-group">
                            <label for="title">Title: </label>
                            <input class="form-control" id="title" type="text" name="title" value="{{ old('title') }}" required>
                        </div>
                    	<div class="form-group">
                    		<label for="body">Body:</label>
                    		<textarea class="form-control" id="body" name="body" rows="8" required>{{ old('body') }}</textarea>
                    	</div>
                        <div class="form-group">
                           <button class="btn btn-primary" type="submit">Publish</button>
                       </div>
                       @if(count($errors))
                       <ul class="alert alert-danger">
                        @foreach($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                    @endif
                </form>

            </div>
        </div>
    </div>
</div>
</div>
@endsection

resources/views/threads/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            @forelse($threads as $thread)
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="level">

                        <h4 class="flex">
                            <a href="{{ $thread->path() }}">{{ $thread->title }}</a>
                        </h4>
                        <strong><small>{{ $thread->replies_count }} {{ str_plural('comment',$thread->replies_count) }}.</small></strong>
                    </div>
                </div>

                <div class="panel-body">

                    <div class="body">
                        {{ $thread->body }}
                    </div>
                </div>
            </div>
            @empty
            <p>There are no relevant results at this time.</p>
            @endforelse
        </div>
    </div>
</div>
@endsection

resources/views/threads/reply.blade.php
<reply :data="{{ $reply }}" inline-template v-cloak>
	<div id="reply-{{ $reply->id }}" class="panel panel-default">
		<div class="panel-heading">
			<div class="level">
				<h5 class="flex">
					
					<a href="/profiles/{{$reply->owner->name}}">{{ $reply->owner->name }}</a> said 
					{{ $reply->created_at->diffForHumans() }}...
				</h5>
				@if(Auth::check())
				<div>
					
					<favorite :reply="{{ $reply }}"></favorite>

				</div>
				@endif
			</div>
		</div>
		<div class="panel-body">
			<div v-if="editing">
				<div class="form-group">
				
					<textarea class="form-control" v-model='body'></textarea>
				</div>
				<button class="btn btn-xs btn-primary" @click="update">Update</button>
				<button class="btn btn-xs btn-link" @click="editing = false">Cancel</button>
			</div>
			<div v-else v-text="originalBody"></div>
			

		</div>
		@can ('update',$reply)
		<div class="panel-footer level">
			<button class="btn btn-xs btn-default mr-1" @click="editing = true">Edit</button>
			<button class="btn btn-xs btn-danger" @click="destroy">Delete</button>
		</div>
		@endcan
	</div>
</reply>

resources/views/threads/show.blade.php
@extends('layouts.app')

@section('content')
<thread-view inline-template :initial-replies-count="{{ $thread->replies_count }}">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="level">
                            <span class="flex">
                                <h4>{{ $thread->title }}</h4>
                            </span>

                            @can('update', $thread)
                            <form action="{{ $thread->path() }}" method="post">
                                {{ csrf_field() }}
                                {{ method_field('DELETE') }}
                                <button class="btn btn-link" type="submit">Delete Thread</button>
                            </form>
                            @endcan
                        </div>
                    </div>

                    <div class="panel-body">

                        {{ $thread->body }}

                    </div>
                </div>

                <replies :data="{{ $thread->replies()->oldest()->get() }}" @removed="repliesCount--" ></replies>

                {{-- $replies->links() --}}


                @if(auth()->check())

                <form action="{{ $thread->path().'/replies' }}" method="post">
                    {{ csrf_field() }}
                    <div class="form-group">
                        <textarea placeholder="Have something to say?" name="body" id="body" class="form-control" rows="5"></textarea>
                    </div>
                    <button type="submit" class="btn btn-default">Post</button>
                </form>
                @else
                <p class="text-center">Please <a href="{{ route('login') }}">sign in</a> to participate in this discussion.</p>
                @endif
            </div>
            <div class="col-md-4">
               <div class="panel panel-default">

                <div class="panel-body">
                    <p>
                        This thread was published {{ $thread->created_at->diffForHumans() }} by 
                        <a href="{{ route('profile',$thread->creator) }}">{{ $thread->creator->name }}</a>, and currently 
                        has <span v-text="repliesCount"></span> {{ str_plural('comment',$thread->replies_count) }}.
                    </p>


                </div>
            </div>
        </div>
    </div>

</div>
</thread-view>
@endsection